[DDCE-2719] Migrated to HMRC-Mongo
hmrc/register-estate-personal-rep-frontend pull request #98
Opened 2022-10-27 11:23 UTC by matthewwardcap

Separate ticket may need adding to update `play-frontend-hmrc`

- Cleaned up dependencies
- Performed migration
- Swapped mockito
- Added repository test

2022-10-27 14:07 UTC, frikit requested changes
- Fix deprecated warnings in build.sbt related to `in`
- Fix depreacted warnings in build.sbt for covearge settings
- Remove repositories from `ScoverageKeys.coverageExcludedFiles` as we should cover them and you added tests
- Delete lines 42-46 in build sbt
- Remove all dependency overrides as most likely you dont need them

2022-10-27 14:07 UTC, frikit commented on project/AppDependencies.scala
>      "org.pegdown"                 %  "pegdown"                  % "1.6.0",
can be deleted

2022-10-28 08:12 UTC, matthewwardcap commented on app/repositories/SessionRepository.scala
> +//  def set(userAnswers: UserAnswers): Future[Boolean] = {
Done

2022-10-28 08:13 UTC, matthewwardcap commented on app/config/FrontendAppConfig.scala
> +  lazy val dropIndexes: Boolean = configuration.getOptional[Boolean]("microservice.services.features.mongo.dropIndexes").getOrElse(true)
Done

2022-10-28 08:20 UTC, matthewwardcap commented on project/AppDependencies.scala
> +    "uk.gov.hmrc"         %% "domain"                         % "8.1.0-play-28"
Seems to be still in use in quite a few files

2022-10-28 08:27 UTC, matthewwardcap commented on project/AppDependencies.scala
>      "org.pegdown"                 %  "pegdown"                  % "1.6.0",
Done

2022-10-28 08:27 UTC, matthewwardcap commented on project/AppDependencies.scala
> +    "com.typesafe.play"   %% "play-json-joda"                 % "2.9.3",
Done

2022-10-28 09:00 UTC, frikit commented
Please update hmrc frontend anyway will do testing and changes are very simple. I will help and list them here.
- Update deps to latest
- fix selector for page name
- delete govuk route

You can see changes in this PR https://github.com/hmrc/register-estate-deceased-settlor-frontend/pull/82/files

2022-10-28 09:51 UTC, frikit approved these changes

2022-10-28 09:51 UTC, merged